[General]
DisplayServer=wayland
Numlock=on

[Theme]
Current=breeze
CursorTheme=breeze_cursors
EnableAvatars=false
DisableAvatarsThreshold=0
FacesDir=/dev/null

[Users]
MaximumUid=60000
MinimumUid=1000
RememberLastUser=false
RememberLastSession=false

[Autologin]
Relogin=false
Session=
User=
